### ISSUE TITLE
Issues installing pysentimiento with pip: UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 7: character maps to <undefined>       [end of output]

### ISSUE THREAD

**Issue by fabianslife** [pysentimiento/pysentimiento#50]
Hello,

thank you so much for this cool python package. i have used it before and i was very happy with it. However, i am currently trying to install it on a nwe machine and i constantly get this error:

Collecting pysentimiento
  Using cached pysentimiento-0.6.7-py3-none-any.whl (38 kB)
Collecting datasets>=1.13.3 (from pysentimiento)
  Using cached datasets-2.11.0-py3-none-any.whl (468 kB)
Collecting emoji<2.0.0,>=1.6.1 (from pysentimiento)
  Using cached emoji-1.7.0.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting spacy<4.0.0,>=3.5.0 (from pysentimiento)
  Using cached spacy-3.5.2-cp311-cp311-win_amd64.whl (12.2 MB)
INFO: pip is looking at multiple versions of pysentimiento to determine which version is compatible with other requirements. This could take a while.
Collecting pysentimiento
  Using cached pysentimiento-0.6.6-py3-none-any.whl (38 kB)
  Using cached pysentimiento-0.6.5-py3-none-any.whl (37 kB)
  Using cached pysentimiento-0.6.4-py3-none-any.whl (37 kB)
  Using cached pysentimiento-0.6.3-py3-none-any.whl (37 kB)
  Using cached pysentimiento-0.6.2-py3-none-any.whl (35 kB)
  Using cached pysentimiento-0.2.5-py3-none-any.whl (15 kB)
Collecting transformers (from pysentimiento)
  Using cached transformers-4.28.1-py3-none-any.whl (7.0 MB)
Collecting emoji (from pysentimiento)     
  Using cached emoji-2.2.0.tar.gz (240 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: torch in c:\users\andre\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pysentimiento) (2.0.0+cu117)
Collecting sklearn (from pysentimiento)
  Using cached sklearn-0.0.post4.tar.gz (3.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Andre\AppData\Local\Temp\pip-build-env-ioc392l4\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Andre\AppData\Local\Temp\pip-build-env-ioc392l4\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\Andre\AppData\Local\Temp\pip-build-env-ioc392l4\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Andre\AppData\Local\Temp\pip-build-env-ioc392l4\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 10, in <module>
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 7: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.        
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by fabianslife** [comment]
Hi, 

Yes, my python version was not compatible with it. Python 3.11 doesn't seem to work without some problems. I solved it by downgrading to 3.10

**Comment by finiteautomata** [comment]
Sorry to know it. I leave this open to add support for python 3.11

**Comment by finiteautomata** [comment]
0.7.2 now supports python 3.11
